#/usr/bin/env python

# Author: Andres Rubio Chavez <andres.rubio.chavez@gmail.com>

import mraa as MRAA

# Tracks
TRACK_LEFT_FWD_PWM_PIN=MRAA.INTEL_EDISON_MINIBOARD_J17_1 #MRAA 0 PWM2
TRACK_LEFT_REV_PWM_PIN=MRAA.INTEL_EDISON_MINIBOARD_J18_1 #MRAA 14 PWM1
TRACK_RIGHT_FWD_PWM_PIN=MRAA.INTEL_EDISON_MINIBOARD_J18_7 #MRAA 20 PWM0
TRACK_RIGHT_REV_PWM_PIN=MRAA.INTEL_EDISON_MINIBOARD_J18_8 #MRAA 21 PWM3
PWM_PERIOD_US=1000

# Turret
TURRET_LEFT_GPIO_PIN=MRAA.INTEL_EDISON_MINIBOARD_J20_4 #MRAA 45 GPIO-45
TURRET_RIGHT_GPIO_PIN=MRAA.INTEL_EDISON_MINIBOARD_J20_5 #MRAA 46 GPIO-47
MUZZLE_UP_GPIO_PIN=MRAA.INTEL_EDISON_MINIBOARD_J20_6 #MRAA 47 GPIO-49
MUZZLE_DOWN_GPIO_PIN=MRAA.INTEL_EDISON_MINIBOARD_J20_7 #MRAA 48 GPIO-15

# Cannon
CANNON_FIRE_GPIO_PIN=MRAA.INTEL_EDISON_MINIBOARD_J18_2 #MRAA 15 GPIO-165
CANNON_SWITCH_GPIO_PIN=MRAA.INTEL_EDISON_MINIBOARD_J19_4 #MRAA 31 GPIO-44

# Lights
HEADLIGHTS_GPIO_PIN=MRAA.INTEL_EDISON_MINIBOARD_J19_5 #MRAA 32 GPIO-46
STOPLIGHT_LEFT_GPIO_PIN=MRAA.INTEL_EDISON_MINIBOARD_J19_6 #MRAA 33 GPIO-48
STOPLIGHT_RIGHT_GPIO_PIN=MRAA.INTEL_EDISON_MINIBOARD_J19_9 #MRAA 36 GPIO-14

# Radio
RADIO_SSP2_CLK=MRAA.INTEL_EDISON_MINIBOARD_J19_10 #MRAA 37 SSP2_CLK
RADIO_SSP2_TXD=MRAA.INTEL_EDISON_MINIBOARD_J19_11 #MRAA 38 SSP2_TXD
RADIO_SSP2_RXD=MRAA.INTEL_EDISON_MINIBOARD_J20_9 #MRAA 50 SSP2_RXD
RADIO_SSP2_FS=MRAA.INTEL_EDISON_MINIBOARD_J20_10 #MRAA 51 SSP2_FS
